sudo: false
language: node_js
node_js:
- 6.9.1
cache:
- apt: true
- directories:
  - node_modules
  - "$(npm config get prefix)/bin/gulp"
before_script:
- npm list -g gulp --depth=0 || npm install -g gulp
- npm list -g typescript --depth=0 || npm install -g typescript
- npm list -g typings --depth=0 || npm install -g typings
- tsc -v
script:
- npm install
- npm prune
- npm rebuild node-sass
- gulp package.prod
after_success:
#- cd dist/ && tar -zcf $HOME/-web-dist-$TRAVIS_BRANCH.tar.gz . && cd ..
#- pushd $HOME && sha256sum web-dist-$TRAVIS_BRANCH.tar.gz > web-dist-$TRAVIS_BRANCH.tar.gz.sha256 && popd
before_cache:
- rvm install 2.1
- ruby --version
- gem install berkshelf
